[package]
name = "smoltcp-tls"
version = "0.1.0"
authors = ["occheung <occheung@connect.ust.hk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aes-gcm = "0.7.0"
chacha20poly1305 = "0.6.0"
byteorder = "1.3.4"
num_enum = "0.5.1"

[dependencies.smoltcp]
version = "0.6.0"
default-features = false
features = ["proto-ipv4", "proto-ipv6", "socket-tcp"]

[dependencies.rand_chacha]
version = "0.2.2"
default-features = false
features = []

[dependencies.rand]
version = "0.7.3"
default-features = false
features = ["getrandom"]

[dependencies.heapless]
version = "0.5.6"
default-features = false
features = []